### PR TITLE
Filters

### LINKED ISSUE #78: Filters for User Permissions/Authentication
Use filters to allow access to pages/functionality. 
Also requires Logout after 20 minutes, httpSession exist.

### PR DESCRIPTION
**Pull request by Austish101**
closes #78 
Filters implementation complete. Also there is a logger that we could use now, may remove later. 
Tested as much as possible, may still be some bugs in rare use cases. 

WHEN ADDING NEW PAGES AND SERVLETS:
These must be added to GlobalAuthenticationFilter, I've commented as best as I can, you should be able to find where it goes.

### CODE REVIEW

**Review by ItsmeHJB — CHANGES_REQUESTED** [review]
Remove unnecessary files

**Review by ItsmeHJB — APPROVED** [review]
Code works fully after removal of files

**Review by ItsmeHJB — CHANGES_REQUESTED** [review]
Can no longer reach the signup page from the login page

**Comment by Austish101** [comment]
Will close and request new PR due to branch changes to solve these issues.

**Pull request closed without merging**
