### PR TITLE
104 forward patient to hosp

### LINKED ISSUE #104: Forward a patient to a hospital or clinic - D/N
Doctor or nurse refers patient elsewhere using the referrals table.

### PR DESCRIPTION
**Pull request by ItsmeHJB**
closes #104 

Code to add a referral to the database, cleaned up referral class to work better. Let me know if I have made unnecessary files like the JSP as I'm not sure I really need it?

### CODE REVIEW

**Comment by m3-welch** [comment]
I don't think you need the addReferrals.jsp, that's more of you want it to be a separate page. Also, is it just doctors that can do referrals? Or can nurses and admins do it too?

**Comment by ItsmeHJB** [comment]
Ah yes, I'll get rid of the JSP and add it to the other dashboards soon

**Comment by ItsmeHJB** [comment]
Updated code to fix the comment

**Review by m3-welch — APPROVED** [review]
Looks good :smile:

**Pull request merged**
